import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/shared/header';

const nunito = Nunito({
  subsets: ['latin'],
  //subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Pizza Online | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={nunito.className}>
        <main className="min-h-screen">
          {/* Alle Seiten haben Header */}
          <Header />
          {/* Alle mögliche Seiten der App */}
          {children}
        </main>
      </body>
    </html>
  );
}
